name: EmporiumStockReloader
# Purges the Cache daily of the Fish Emporium and Virtual Tank Fish pages for the Insaniquarium Wiki. Allows the infobox to update automatically.

on:
  schedule:
    # Updates every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge The Fish Emporium
        env:
          BOT_USERNAME: ${{ secrets.WIKI_BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.WIKI_BOT_PASSWORD }}
        run: |
          curl -X POST --user "$BOT_USERNAME:$BOT_PASSWORD" \
            -d "action=purge&titles=The_Fish_Emporium&format=json" \
            "https://insaniquarium.fandom.com/api.php"

      - name: Purge Virtual Tank Fish
        env:
          BOT_USERNAME: ${{ secrets.WIKI_BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.WIKI_BOT_PASSWORD }}
        run: |
          curl -X POST --user "$BOT_USERNAME:$BOT_PASSWORD" \
            -d "action=purge&titles=Virtual_Tank_Fish&format=json" \
            "https://insaniquarium.fandom.com/api.php"
            
      - name: Purge Template:Infobox/VTShopStock
        env:
          BOT_USERNAME: ${{ secrets.WIKI_BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.WIKI_BOT_PASSWORD }}
        run: |
          curl -X POST --user "$BOT_USERNAME:$BOT_PASSWORD" \
            -d "action=purge&titles=Template:Infobox/VTShopStock&format=json" \
            "https://insaniquarium.fandom.com/api.php"
      - name: Update keepalive timestamp
        if: github.event.schedule == '0 0 * * 1'
        run: |
          git config --global user.name "wiki-bot"
          git config --global user.email "bot@example.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} temprepo
          cd temprepo
          date > .keepalive
          git add .keepalive
          git commit -m "Keepalive update"
          git push
